Add vboxmanage-createvm with multiple os type options

diff --git a/unix-shell-script-kit b/unix-shell-script-kit
--- a/unix-shell-script-kit
+++ b/unix-shell-script-kit
@@ -1,38 +1,43 @@
 #!/bin/sh
 
-# POSIX shell script kit.
+# Unix shell script kit.
 #
-# The POSIX shell script kit is one file of helper functions and constants.
+# Unix shell script kit is a collection of utility functions and constants.
 #
-# These work for bash, zsh, ksh, dash, sh, and any other modern POSIX shell.
+# The kit works with POSIX shells, including bash, zsh, dash, ksh, sh, etc.
 #
-# You can include this file in your own scripts, or copy anything you want.
+# All suggestions are welcome and appreciated.
 #
-# This file is free libre open source software, created by SixArm.
+# ## Download
 #
-# Constructive feedback is welcome and appreciated.
-#
-# To download this file:
+# Download the kit as one file that has everything:
 #
 # ```sh
-# curl -O "https://raw.githubusercontent.com/SixArm/posix-shell-script-kit/main/posix-shell-script-kit"
+# curl -O "https://raw.githubusercontent.com/SixArm/unix-shell-script-kit/main/unix-shell-script-kit"
 # ```
 #
-# To include this file in your own script, in the same directory:
+# ## Source
+#
+# To use the kit in your own script, you source the kit like this:
 #
 # ```sh
-# # Include https://github.com/SixArm/posix-shell-script-kit
-# . "$(dirname "$(readlink -f "$0")")/posix-shell-script-kit"
+# . /your/path/here/unix-shell-script-kit
+# ```
+#
+# To use the kit in your own script, in the same directory, you source the kit like this:
+#
+# ```sh
+# . "$(dirname "$(readlink -f "$0")")/unix-shell-script-kit"
 # ```
 #
 # ## Tracking
 #
-#   * Package: posix-shell-script-kit
-#   * Version: 11.0.5
+#   * Package: unix-shell-script-kit
+#   * Version: 12.1.2
 #   * Created: 2017-08-22T00:00:00Z
-#   * Updated: 2023-03-24T13:23:36Z
+#   * Updated: 2023-11-25T01:11:42Z
 #   * License: GPL-2.0 or GPL-3.0 or contact us for more
-#   * Website: https://github.com/sixarm/posix-shell-script-kit
+#   * Website: https://github.com/sixarm/unix-shell-script-kit
 #   * Contact: Joel Parker Henderson (joel@sixarm.com)
 
 ##
@@ -51,26 +56,39 @@
 #
 # * 3-63 are for a program-specific exit codes.
 #
-# * 64-78 are based on sysexits documentation from the 1980's.
+# * 64-78 are based on BSD sysexits <https://man.openbsd.org/sysexits.3>
 #
 # * 80-119 are SixArm conventions that we find useful in many programs.
 #
-# Many POSIX shells use exit codes 126 and 127 to signal specific error status:
+# Many shells use exit codes 126-128 to signal specific error status:
 #
-# * 126 is for the shell and indicates command found but not executable.
+# * 126 is for the shell and indicates command found but is not executable.
 #
 # * 127 is for the shell and indicate command not found.
 #
-# Many POSIX shells use exit codes above 128 in their $? representation of the
-# exit status to encode the signal number of a process being killed.
+# * 128 is for invalid argument to exit.
 #
-# The pre-defined exit codes from sysexits can be used, so the caller of the
-# process can get a rough estimation about the failure class without looking up
-# the source code.
+# Many shells use exit codes above 128 in their $? representation of the exit
+# status to encode the signal number of a process being killed.
 #
-# See https://man.openbsd.org/sysexits.3
+# * 128+n means fatal error signal "n"
 #
-# We recommend:
+# * Example: 130 means terminated by ctrl-C (because ctrl-c is signal 2)
+#
+# * Example: 137 means terminated by kill -9 (because 128 + 9 = 137)
+#
+# Finally, the highest exit code:
+#
+# * 255 Exit status out of range (exit takes integer args 0-255)
+#
+# Be aware that on some shells, ut of range exit values can result in unexpected
+# exit codes. An exit value greater than 255 returns an exit code modulo 256.
+#
+# * Example: exit 257 becomes exit 1 (because 257 % 256 = 1)
+#
+# * Caution: exit 256 becomes exit 0, which probably isn't what you want.
+#
+# For some typical needs that we encounter, we can suggest these:
 #
 # * Authentication issues: exit $EXIT_NOUSER
 #
@@ -111,7 +129,7 @@ EXIT_USAGE=2
 
 # Data Err
 #
-# The input data was incorrect in some way. 
+# The input data was incorrect in some way.
 #
 # This should only be used for user's data and not system files.
 #
@@ -127,7 +145,7 @@ EXIT_NOINPUT=66
 
 # No User
 #
-# The user specified did not exist. 
+# The user specified did not exist.
 #
 # E.g. for email addresses, or remote logins, or authentication issues, etc.
 #
@@ -135,7 +153,7 @@ EXIT_NOUSER=67
 
 # No Host
 #
-# The host specified did not exist. 
+# The host specified did not exist.
 #
 # E.g. for email addresses, or network requests, or webs links, etc.
 #
@@ -143,7 +161,7 @@ EXIT_NOHOST=68
 
 # Unavailable
 #
-# A service is unavailable. 
+# A service is unavailable.
 #
 # E.g. a support program or file does not exist. This can also be a catchall
 # message when something does not work, but you do not know why.
@@ -152,7 +170,7 @@ EXIT_UNAVAILABLE=69
 
 # Software
 #
-# An internal software error has been detected. 
+# An internal software error has been detected.
 #
 # This should be limited to non-operating system related errors as possible.
 #
@@ -160,7 +178,7 @@ EXIT_SOFTWARE=70
 
 # OS Err
 #
-# An operating system error has been detected. 
+# An operating system error has been detected.
 #
 # E.g. errors such as "cannot fork", "cannot create pipe", or getuid returns a
 # user that does not exist in the passwd file, etc.
@@ -175,7 +193,7 @@ EXIT_OSERR=71
 EXIT_OSFILE=72
 
 # Can't Create
-# 
+#
 # A user-specified output (e.g. a file) cannot be created.
 #
 EXIT_CANTCREATE=73
@@ -203,7 +221,7 @@ EXIT_PROTOCOL=76
 
 # No Perm
 #
-# You did not have sufficient permission to perform the operation. 
+# You did not have sufficient permission to perform the operation.
 #
 # This is not for file system problems, which use EXIT_NOINPUT or
 # EXIT_CANTCREATE, but for higher level permissions, authorizations, etc.
@@ -268,15 +286,24 @@ EXIT_CONFLICT=90
 # Something is prohibited due to law, or warrant, or court order, etc.
 #
 # Akin to HTTP status code 451 Unavailable For Legal Reasons (RFC 7725).
+#
 EXIT_UNLAWFUL=91
 
 # Payment Issue
 #
 # Something needs a credit card, or invoice, or billing, etc.
 #
-# Akin to HTTP status code 402 Payment Required.
+# Akin to a superset of HTTP status code 402 Payment Required.
 #
 EXIT_PAYMENT_ISSUE=92
+
+# Quota Issue
+#
+# A quota is reached, such as exhausting a free trial, out of fuel, etc.
+#
+# Akin to a superset of HTTP status code 429 Too Many Requests.
+#
+EXIT_QUOTA_ISSUE=93
 
 # Exit codes 100+ for process runtime issues...
 
@@ -352,7 +379,7 @@ EXIT_FUTURE=119
 #
 # The special exit code 125 should be used when the current source code cannot
 # be tested. If the script exits with this code, the current revision will be
-# skipped (see git bisect skip above). 
+# skipped (see git bisect skip above).
 #
 # Value 125 was chosen as the highest sensible value to use for this
 # purpose, because 126 and 127 are used by shells to signal specific errors.
@@ -372,6 +399,22 @@ EXIT_COMMAND_FOUND_BUT_NOT_EXECUTABLE=126
 # A command is not found.
 #
 EXIT_COMMAND_NOT_FOUND=127
+
+# Exit code invalid
+#
+# The exit code is invalid.
+#
+# Compare EXIT_CODE_OUT_OF_RANGE=255
+#
+EXIT_CODE_INVALID=128
+
+# Exit code out of range
+#
+# The exit code is out of range i.e. not in 0-255.
+#
+# Compare EXIT_CODE_INVALID=128
+#
+EXIT_CODE_INVALID=128
 
 ##
 # Input/output helpers
@@ -592,6 +635,93 @@ older() {
 # Validation helpers
 ##
 
+# directory_exists: does a directory exist?
+#
+# Example:
+# ```
+# directory_exists /usr
+# => true
+#
+# directory_exists /loremipsum
+# => false
+# ```
+directory_exists() {
+        test -d "$1"
+}
+
+# directory_exists_or_die: ensure a directory exists.
+#
+# Example:
+# ```
+# directory_exists_or_die /usr
+# => true
+#
+# directory_exists_or_die /loremipsum
+# STDERR=> Directory needed: /loremipsum
+# => exit $EXIT_IOERR
+# ```
+directory_exists_or_die() {
+        directory_exists "$1" || die "$EXIT_IOERR" "Directory needed: $1"
+}
+
+# file_exists: does a file exist?
+#
+# Example:
+# ```
+# file_exists foo.txt
+# => true
+#
+# file_exists loremipsum.txt
+# => false
+# ```
+file_exists() {
+        test -f "$1"
+}
+
+# file_exists_or_die: ensure a file exists.
+#
+# Example:
+# ```
+# file_exists_or_die foo.txt
+# => true
+#
+# file_exists_or_die loremipsum.txt
+# STDERR=> File needed: loremipsum.txt
+# => exit $EXIT_IOERR
+# ```
+file_exists_or_die() {
+        file_exists "$1" || die "$EXIT_IOERR" "File needed: $1"
+}
+
+# symlink_exists: does a symlink exist?
+#
+# Example:
+# ```
+# symlink_exists foo.txt
+# => true
+#
+# symlink_exists loremipsum.txt
+# => false
+# ```
+symlink_exists() {
+        test -h "$1"
+}
+
+# symlink_exists_or_die: ensure a symlink exists.
+#
+# Example:
+# ```
+# symlink_exists_or_die foo.txt
+# => true
+#
+# symlink_exists_or_die loremipsum.txt
+# STDERR=> Symlink needed: loremipsum.txt
+# => exit $EXIT_IOERR
+# ```
+symlink_exists_or_die() {
+        symlink_exists "$1" || die "$EXIT_IOERR" "Symlink needed: $1"
+}
+
 # command_exists: does a command exist?
 #
 # Example:
@@ -613,8 +743,8 @@ command_exists() {
 # command_exists_or_die grep
 # => true
 #
-# command_exists_or_die curl
-# STDERR=> Command needed: curl
+# command_exists_or_die loremipsum
+# STDERR=> Command needed: loremipsum
 # => exit 1
 # ```
 command_exists_or_die() {
@@ -960,7 +1090,10 @@ touch_format() {
 
 # select_character_class: get a string's characters that match a class, with optional offset and length.
 #
-# Syntax: select_character_class <string> <class> [offset [length]]
+# Syntax:
+# ```
+# select_character_class <string> <class> [offset [length]]
+# ```
 #
 # Example with character class:
 # ```
@@ -988,7 +1121,10 @@ select_character_class() {
 
 # reject_character_class: get a string's characters that don't match a class, with optional offset and length.
 #
-# Syntax: reject_character_class <string> <class> [offset [length]]
+# Syntax:
+# ```
+# reject_character_class <string> <class> [offset [length]]
+# ```
 #
 # Example with character class:
 # ```
@@ -1012,6 +1148,267 @@ reject_character_class() {
 	offset=${3:-0}
 	length=${4:-${#string}}
 	printf %s\\n ${string:$offset:$length}
+}
+
+##
+# Random character helpers
+##
+
+# random_char
+#
+# Syntax:
+# ```
+# random_char [characters [length]]
+# ```
+#
+# Example:
+# ```
+# random_char ABCDEF 8
+# => CBACBFDD
+#```
+#
+# Example hexadecimal digit uppercase:
+# ```
+# random_char 0-9A-F 8
+# => FC56A95C
+#```
+#
+# Example character class for uppercase letters:
+# ```
+# random_char '[:upper:]' 8
+# => ZMGIQBJB
+#```
+#
+# POSiX character classes for ASCII characters:
+#
+# ```
+# Class       Pattern        Description
+# ----------  -------------  -----------
+# [:upper:]   [A-Z]          uppercase letters
+# [:lower:]   [a-z]          lowercase letters
+# [:alpha:]   [A-Za-z]       uppercase letters and lowercase letters
+# [:alnum:]   [A-Za-z0-9]    uppercase letters and lowercase letters and digits
+# [:digit:]   [0-9]          digits
+# [:xdigit:]  [0-9A-Fa-f]    hexadecimal digits
+# [:punct:]                  punctuation (all graphic characters except letters and digits)
+# [:blank:]   [ \t]          space and TAB characters only
+# [:space:]   [ \t\n\r\f\v]  whitespace characters (space, tab, newline, return, feed, vtab)
+# [:cntrl:]                  control characters
+# [:graph:]   [^ [:cntrl:]]  graphic characters (all characters which have graphic representation)
+# [:print:]   [[:graph:] ]   graphic characters and space
+# ```
+random_char() {
+        chars=${1:-'[:graph:]'}
+        len=${2-1}
+        printf "%s\n" $(LC_ALL=C < /dev/urandom tr -dc "$chars" | head -c"$len")
+}
+
+# random_char_alnum: random characters using [:alnum:] class.
+#
+# Syntax:
+# ```
+# random_char_alnum [length]
+# ```
+#
+# Example:
+# ```
+# random_char_alnum 8
+# => 1Yp7M7wc
+#```
+random_char_alnum() {
+        random_char '[:alnum:]' "$@"
+}
+
+# random_char_alpha: random characters using [:alpha:] class.
+#
+# Syntax:
+# ```
+# random_char_alnum [length]
+# ```
+#
+# Example:
+# ```
+# random_char_alpha 8
+# => dDSmQlYD
+#```
+random_char_alpha() {
+        random_char '[:alpha:]' "$@"
+}
+
+# random_char_blank: random characters using [:blank:] class.
+#
+# Syntax:
+# ```
+# random_char_alnum [length]
+# ```
+#
+# Example:
+# ```
+# random_char_blank 8
+# => "  \t  \t  \t"
+#```
+random_char_blank() {
+        random_char '[:blank:]' "$@"
+}
+
+# random_char_cntrl: random characters using [:cntrl:] class.
+#
+# Syntax:
+# ```
+# random_char_alnum [length]
+# ```
+#
+# Example:
+# ```
+# random_char_cntrl 8
+# => "^c^m^r^z^a^e^p^u"
+#```
+random_char_cntrl() {
+        random_char '[:cntrl:]' "$@"
+}
+
+# random_char_digit: random characters using [:digit:] class.
+#
+# Syntax:
+# ```
+# random_char_alnum [length]
+# ```
+#
+# Example:
+# ```
+# random_char_digit 8
+# => 36415110
+#```
+random_char_digit() {
+        random_char '[:digit:]' "$@"
+}
+
+# random_char_graph: random characters using [:graph:] class.
+#
+# Syntax:
+# ```
+# random_char_alnum [length]
+# ```
+#
+# Example:
+# ```
+# random_char_graph 8
+# => e'2-3d+9
+#```
+random_char_graph() {
+        random_char '[:graph:]' "$@"
+}
+
+# random_char_lower: random characters using [:lower:] class.
+#
+# Syntax:
+# ```
+# random_char_alnum [length]
+# ```
+#
+# Example:
+# ```
+# random_char_lower 8
+# => pgfqrefo
+#```
+random_char_lower() {
+        random_char '[:lower:]' "$@"
+}
+
+# random_char_lower_digit: random characters using [:lower:][:digit] classes
+#
+# Syntax:
+# ```
+# random_char_alnum [length]
+# ```
+#
+# Example:
+# ```
+# random_char_lower_digit 8
+# => 69m7o83i
+#```
+random_char_lower_digit() {
+        random_char '[:lower:][:digit:]' "$@"
+}
+
+# random_char_upper: random characters using [:upper:] class.
+#
+# Syntax:
+# ```
+# random_char_alnum [length]
+# ```
+#
+# Example:
+# ```
+# random_char_upper 8
+# => EGXUHNIM
+#```
+random_char_upper() {
+        random_char '[:upper:]' "$@"
+}
+
+# random_char_upper_digit: random characters using [:upper:][:digit:] classes
+#
+# Syntax:
+# ```
+# random_char_alnum [length]
+# ```
+#
+# Example:
+# ```
+# random_char_upper_digit 8
+# => L2PT37H6
+#```
+random_char_upper_digit() {
+        random_char '[:upper:][:digit:]' "$@"
+}
+
+# random_char_print: random characters using [:print:] class.
+#
+# Syntax:
+# ```
+# random_char_alnum [length]
+# ```
+#
+# Example:
+# ```
+# random_char_print 8
+# => ),zN87K;
+#```
+random_char_print() {
+        random_char '[:print:]' "$@"
+}
+
+# random_char_space: random characters using [:space:] class.
+#
+# Syntax:
+# ```
+# random_char_alnum [length]
+# ```
+#
+# Example:
+# ```
+# random_char_space 8
+# => "\n \t\r \v \f"
+#```
+random_char_space() {
+        random_char '[:space:]' "$@"
+}
+
+# random_char_xdigit: random characters using [:xdigit:] class.
+#
+# Syntax:
+# ```
+# random_char_alnum [length]
+# ```
+#
+# Example:
+# ```
+# random_char_xdigit 8
+# => eC3Ce9eD
+#```
+random_char_xdigit() {
+        random_char '[:xdigit:]' "$@"
 }
 
 ##
@@ -1156,7 +1553,7 @@ assert_empty() {
 # STDERR=> assert_not_empty
 # ```
 assert_not_empty() {
-        [ -z "$1" ] || err assert_empty "$@"
+        [ -z "$1" ] || err assert_not_empty "$@"
 }
 
 # assert_int_eq: assert an integer is equal to another integer.
@@ -1529,10 +1926,14 @@ file_ends_with_newline() {
 #
 user_dir(){
 	upper=$(printf %s\\n "$1" | tr '[:lower:]' '[:upper:]')
+	x=$(set +u; eval printf "%s\\\\n" \$${upper}_DIR)
+        if [ -n "$x" ]; then printf %s\\n "$x"; return; fi
+	x=$(set +u; eval printf "%s\\\\n" \$${upper}_HOME)
+        if [ -n "$x" ]; then printf %s\\n "$x"; return; fi
+	x=$(set +u; eval printf "%s\\\\n" \$XDG_${upper}_DIR)
+        if [ -n "$x" ]; then printf %s\\n "$x"; return; fi
+	x=$(set +u; eval printf "%s\\\\n" \$XDG_${upper}_HOME)
+        if [ -n "$x" ]; then printf %s\\n "$x"; return; fi
 	lower=$(printf %s\\n "$1" | tr '[:upper:]' '[:lower:]')
-	a=$(eval printf "%s\\\\n" \$${upper}_DIR)
-	b=$(eval printf "%s\\\\n" \$${upper}_HOME)
-	c=$(eval printf "%s\\\\n" \$XDG_${upper}_DIR)
-	d=$(eval printf "%s\\\\n" \$XDG_${upper}_HOME)
-        printf %s\\n "${a:=${b:=${c:=${d:=$HOME/$lower}}}}"
+        printf %s\\n "$HOME/$lower"
 }
